### ISSUE TITLE
What API key we have to use

### ISSUE THREAD

**Issue by FoudreTeam** [exaroton/exaroton-bungeecord#1]
hello, I want to use this plugin for a bungee cord network and i've installed BungeeGuard and copy pasted the token in the config file of exaroton but it's not working and I get this error in the proxy's console 

[ExarotonBungeePlugin] An API Error occurred!
com.exaroton.api.APIException: Unauthorized
    at com.exaroton.api.APIRequest.request(APIRequest.java:72)
    at com.exaroton.api.ExarotonClient.getServers(ExarotonClient.java:186)
    at com.exaroton.bungee.ExarotonPlugin.fetchServers(ExarotonPlugin.java:185)
    at com.exaroton.bungee.ExarotonPlugin.findServer(ExarotonPlugin.java:202)
    at com.exaroton.bungee.subcommands.StartServer.execute(StartServer.java:31)
    at com.exaroton.bungee.ExarotonCommand.lambda$execute$0(ExarotonCommand.java:81)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by JulianVennen** [comment]
You need the API token of your exaroton account.
You can copy it on https://exaroton.com/account/

**Comment by FoudreTeam** [comment]
My server is not running on exaroton

**Comment by JulianVennen** [comment]
Your proxy might not run on exaroton, but some of your servers do (otherwise why are you using this plugin?)

**Comment by FoudreTeam** [comment]
Oh i've found where the api key is and I have no servers on exaroton and i'm using this plugin to start my servers without going to the panel

**Comment by JulianVennen** [comment]
You can obviously only start exaroton servers with this plugin.
If you don't have any servers on exaroton this plugin does nothing

**Comment by FoudreTeam** [comment]
oh ok

**Comment by FoudreTeam** [comment]
but in the desc it says that it can work if we are not on exaroton

**Comment by JulianVennen** [comment]
It works if your proxy is not running on exaroton

**Comment by JulianVennen** [comment]
We obviously can't magically start servers running literally anywhere

**Comment by FoudreTeam** [comment]
oh
 thank you

**Comment by JammyHuman** [comment]
loll

**Comment by JammyHuman** [comment]
sorry for useless comment

**Comment by JammyHuman** [comment]
I deleted them
